### ISSUE TITLE
How to use Render in CollectionView

### ISSUE THREAD

**Issue by kawasemi081** [alexdrone/Render#18]
Hi Alex,

Let me know about how to use Render in CollectionView, please.

Can we use this method for adding next items when user scroll down on the bottom of the list?
If not,  is there another way to do?

https://github.com/alexdrone/Render/blob/befc59d4edff75711acf73eae3c10e48bd32665d/Render/ComponentCell.swift#L173-L177

If our collectionView supported the horizontal scroll UI, what sort of stuff should we care about so that we can create with Render?

**Comment by gmckenzi** [comment]
At the risk of hijacking this question, I'm trying to determine how to use Render with UITableView. Based on my testing so far, I don't see any special handling of UITableView in Render. For instance, I am guessing that in order to get a table view or collection view to behave within a Render view, I will need to manage the size and content of the table view manually. In my case I have a UIScrollView that contains a number of views all arranged by Render, including a UITableView. While I can put a table view inside a flex layout, I think I'll need to size it myself based on the number of rows etc. and manage the cell content and size. So, my table view will be an island of manually handled content within my flex layout. I don't believe Render has the ability determine the size of the table view after population and adjust the surrounding layout accordingly.

**Comment by alexdrone** [comment]
If you want to use tableViews or collectionViews I suggest you to use
https://github.com/alexdrone/Buffer

Is complementary to Render, and it has component-oriented tableviews and collectionview.
