### ISSUE TITLE
Using Yoga via cocoa pods

### ISSUE THREAD

**Issue by emilsjolander** [alexdrone/Render#32]
Hey! I'm the maintainer of Yoga and just stumbled upon this project. Cool stuff! I'm wondering if there is a reason for not using Yoga via cocoa pods and instead having a fork of the code? Cocoa pods support in Yoga is quite new so that might be the case :)

**Comment by alexdrone** [comment]
Hey Emil! Been following Yoga since the early days of "css-layout" :) Amazing work! 
I've been through a major rewrite of Render - making sure that all of the layout logic was delegated to YogaKit - and I'm very happy with the result.

Didn't know that Yoga had Cocoapods support (probably because as you said it was added quite recently) - on the other hand I'd like Render to be pretty agnostic when it comes to how to consume the library, so maybe a vanilla git submodule would work better to keep Render in sync with latests YogaKit? 

Also, I'm very interested in your feedback for the project. :) :)

**Comment by emilsjolander** [comment]
Haven't had a chance to look at the library or play with it much yet but will make sure to do so soon 👍 Yeah git submodule would probably work equally well :) 

Glad that Yoga is working out well for you, if you have any issues we are happy to work with you to fix them, just post an issue 💯
